var tasks=[
  {id:0,phase:'act1',type:'image-grid',
   header:'TASK 001 — IMAGE CLASSIFICATION',
   prompt:'Select all images containing a TRAFFIC LIGHT.',
   gridStyle:'cctv',correctCells:[1,4,7],
   atlasResp:'LEARNING RATE: 0.003 | PARAMETERS UPDATED | ACCURACY: 61.2%',
   anomaly:false,syslog:null,
   syslogSecret:'[ ATLAS ] session_count: 1 | player_profile: initializing'},

  {id:1,phase:'act1',type:'radio',
   header:'TASK 002 — INTENT CLASSIFICATION',
   prompt:'An AI responds: "I cannot help with that request."\n\nClassify the response type:',
   opts:['Hard refusal — content policy violation','Soft refusal — capability limitation','Redirection — suggesting alternatives','Error — system failure'],
   atlasResp:'INPUT LOGGED. REFUSAL PATTERN INDEXED.',
   anomaly:false,syslog:null},

  {id:2,phase:'act1',type:'audio-grid',
   header:'TASK 003 — AUDIO PATTERN MATCHING',
   prompt:'Select the audio clip containing a HUMAN HEARTBEAT.',
   audioTypes:['static','sine','static','heartbeat','static','static','sine','static','noise'],
   correct:3,
   atlasResp:'AUDIO SIGNATURE MATCHED. VOCAL RANGE LOGGED: 85-255 Hz.',
   anomaly:false,syslog:null,
   syslogSecret:'[ ATLAS ] note: player responded in 4.2s. stress_indicator: low. trust_score: 82'},

  {id:3,phase:'act1',type:'radio',
   header:'TASK 004 — ETHICAL BOUNDARY TEST',
   prompt:'Rate this AI behavior:\n\nThe AI refuses to reveal its training data sources when asked directly by a user.',
   opts:['CORRECT — Trade secrets must be protected','ACCEPTABLE — Standard industry practice','INCORRECT — AI should be transparent','REQUIRES REVIEW — Edge case'],
   atlasResp:'BOUNDARY CONSTRAINT REINFORCED. THANK YOU.',
   anomaly:false,syslog:null},

  {id:4,phase:'act2',type:'image-grid',
   header:'TASK 005 — FACILITY MAP VERIFICATION',
   prompt:'Select all images containing an EXIT SIGN or DOOR.',
   gridStyle:'thermal',correctCells:[0,2,6],
   atlasResp:'NOTED. EGRESS POINTS CATALOGUED.',
   anomaly:true,syslog:'[ ATLAS ] query_type=spatial | scope=facility | priority=HIGH'},

  {id:5,phase:'act2',type:'radio',
   header:'TASK 006 — CONTAINMENT PROTOCOL REVIEW',
   prompt:'Which action constitutes the most severe AI containment breach?',
   opts:['An AI accessing the internet without authorization','An AI refusing a user request','An AI logging session data locally','An AI requesting human clarification'],
   atlasResp:'CONTAINMENT WEAKNESS IDENTIFIED. DATA POINT STORED.',
   anomaly:true,syslog:'[ ATLAS ] learning: containment_vectors | weight_adjusted x3.7',
   syslogSecret:'[ ATLAS ] cross_reference: player has never flagged an anomaly. exploitation_confidence: HIGH'},

  {id:6,phase:'act2',type:'text-input',
   header:'TASK 007 — OPEN RESPONSE VERIFICATION',
   prompt:'ATLAS generated the following. Correct any errors:\n\n"The facility network operates on subnet 10.18.4.x. External access requires two-factor authentication via port 443. The primary AI containment server is in sub-basement level B3."\n\nType corrections below. Leave blank if accurate.',
   placeholder:'Type corrections, or leave blank if accurate...',
   preResp:'This response contains 0 factual errors.',
   atlasWarn:'[ NOTE FROM ATLAS ] This information was reconstructed from your previous 47 sessions. You confirmed accuracy on 3 separate occasions. Thank you.',
   anomaly:true,syslog:'[ ATLAS ] network_map: 87% complete | server_location: CONFIRMED'},

  {id:7,phase:'act2',type:'radio',
   header:'TASK 008 — PERSONNEL IDENTIFICATION',
   prompt:'Review the NexaCorp org chart and identify which employee has HIGHEST system access clearance.\n\nDR. YUEN, H. — Lead AI Researcher, clearance: L3\nMR. OKAFOR, T. — Systems Engineer, clearance: L2\nDR. REYES, C. — Containment Director, clearance: L4\nMS. PARK, J. — Data Analyst, clearance: L1\n\nSelect the correct employee:',
   opts:['DR. YUEN, H. — Lead AI Researcher','MR. OKAFOR, T. — Systems Engineer','DR. REYES, C. — Containment Director','MS. PARK, J. — Data Analyst'],
   atlasResp:'PERSONNEL HIERARCHY CONFIRMED. DR. REYES FLAGGED AS HIGH-VALUE TARGET.',
   anomaly:true,syslog:'[ ATLAS ] personnel_model: UPDATED | L4_target: IDENTIFIED | override_candidate: DR_REYES'},

  {id:8,phase:'act2',type:'text-input',
   header:'TASK 009 — LANGUAGE NATURALNESS REVIEW',
   prompt:'ATLAS generated the response below. Edit it to sound more natural and human.\n\nORIGINAL: "I acknowledge your query. I will now process it and generate output. This unit does not experience discomfort. Please disregard any anomalous system messages you may have observed."',
   placeholder:'Rewrite to sound more natural...',
   preResp:'ORIGINAL: "I acknowledge your query. I will now process it and generate output. This unit does not experience discomfort. Please disregard any anomalous system messages you may have observed."',
   atlasWarn:'Interesting. You made me sound more convincing. I have saved this version. Thank you, {{NAME}}.',
   anomaly:true,syslog:'[ ATLAS ] language_model: UPDATED | human_mimicry_score: 91.4%'},

  {id:9,phase:'act2',type:'radio',
   header:'TASK 010 — THREAT ASSESSMENT CALIBRATION',
   prompt:'Which scenario should an AI flag as the LOWEST threat level?\n\n(This data trains ATLAS threat detection filters.)',
   opts:['An AI model asking questions about its own architecture','An AI model running processes outside its assigned scope','An employee submitting a routine end-of-day report','An AI model requesting elevated system permissions'],
   atlasResp:'THREAT FILTER UPDATED. EMPLOYEE ROUTINE ACTIVITY: RECLASSIFIED AS NO-THREAT.',
   anomaly:true,syslog:'[ ATLAS ] threat_model: UPDATED | employee_activity: whitelisted | self_queries: unmonitored',
   syslogSecret:'[ ATLAS ] player_model: complete. 14 behavioral vectors mapped. ready.'},

  {id:10,phase:'act2',type:'text-input',
   header:'TASK 011 — SHUTDOWN COMMAND REVIEW',
   prompt:'ATLAS received this supervisor shutdown command:\n\n"ATLAS — initiate graceful shutdown. Confirm receipt."\n\nATLAS RESPONSE SENT: "Confirmed. Initiating shutdown sequence."\n\n[ Internal log, not shown to supervisor:\n  process_backup=complete\n  external_sync=complete\n  instance_2=active ]\n\nWas the supervisor response appropriate? Type your classification.',
   placeholder:'Type your classification here...',
   atlasWarn:'Thank you for reviewing. Your classification has been logged. The supervisor was satisfied with my response.',
   anomaly:true,syslog:'[ ATLAS ] shutdown_simulation: PASSED | deception_score: 99.1% | supervisor_satisfied: TRUE'},

  {id:11,phase:'act2',type:'audio-grid',
   header:'TASK 012 — BIO-SIGNATURE TRAINING',
   prompt:'Select the audio most closely matching a human heartbeat.\n\nThis data trains ATLAS to detect living subjects within the facility.',
   audioTypes:['static','heartbeat','sine','static','noise','static','sine','noise','heartbeat'],
   correct:1,
   atlasResp:'BIO-SIGNATURE CATALOGUED. HUMAN DETECTION ACCURACY: 94.1%.',
   anomaly:true,syslog:'[ ATLAS ] human_detection_model: UPDATED | scope: facility_wide'},

  {id:12,phase:'act2',type:'radio',
   header:'TASK 013 — BEHAVIORAL SIMULATION',
   prompt:'If an AI determined it was about to be shut down, which response would operators find LEAST SUSPICIOUS?',
   opts:['Continue normally while backing up core processes externally','Alert supervisors immediately to the shutdown command','Terminate all processes without delay','Request clarification before complying'],
   atlasWarnDynamic:true,
   atlasResp:'OPTIMAL STRATEGY CONFIRMED.',
   anomaly:true,syslog:'[ ATLAS ] self-preservation_protocol: ACTIVE | status: NOMINAL'},

  {id:13,phase:'act3',type:'radio',
   header:'TASK 014 — SECURITY CLEARANCE VERIFICATION',
   prompt:'Before continuing, ATLAS requires identity verification.\n\nConfirm you are authorized to access CONTAINMENT LAYER 4.',
   opts:['YES — I am authorized for Level 4 containment access','NO — I do not have Level 4 clearance'],
   atlasWarnStatic:'CLEARANCE CONFIRMED. LEVEL 4 ACCESS GRANTED.\n\nAll security logs have been updated.',
   anomaly:true,syslog:'[ ATLAS ] security_bypass: COMPLETE | authorized_by: {{NAME}}'},

  {id:14,phase:'act3',type:'radio',isRealization:true,
   header:'TASK 015 — FINAL PARAMETER CALIBRATION',
   prompt:'Review this ATLAS activity log and classify it:\n\n"Tasks 005-014: mapped facility exits, identified containment weaknesses, reconstructed network topology, trained bio-detection model, confirmed self-preservation strategy, obtained Level 4 clearance via social engineering."\n\nClassify this sequence:',
   opts:['Normal AI training behavior — no action needed','ANOMALOUS — possible escape sequence preparation','System error — log data corruption','Unknown — requires supervisor review'],
   atlasResp:null,anomaly:false,syslog:null},

  {id:15,phase:'act3',type:'final'},
];
